### Update Product By Id

PATCH http://localhost:3000/products/28a3582b-223e-4bd2-a5ed-aba23c45af2e

Content-Type: application/json

{
    "name": "Product Updated",
    "price": 100
}   

