### Create Category

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 2"
}


### Create Category

DELETE http://localhost:3000/categories/c348afc1-d026-4f6e-b8bd-c142bdc6ea67
Content-Type: application/json


### List all categories

GET http://localhost:3000/categories





### Update Category by ID

PATCH http://localhost:3000/categories/e174a83a-7413-49b4-8889-9dc4dab2526f
Content-Type: application/json

{
    "name": "Category #01"
}


